---
- name: Disable swap (fstab)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  register: swap

- name: Disable swap (swapoff)
  ansible.builtin.shell:
    cmd: swapoff -a
  when: swap.changed is true

- name: Create /etc/modules-load.d/k8s.conf 
  ansible.builtin.copy:
    src: k8s_modules
    dest: /etc/modules-load.d/k8s.conf
  register: k8s_modules

- name: Load modules
  ansible.builtin.shell:
    cmd: modprobe -a overlay br_netfilter
  when: k8s_modules.changed is true

<<<<<<< HEAD:provision/ansible/roles/k8s-prerequisite/tasks/main.yaml
- name: Create /etc/sysctl.d/k8s.conf
=======
- name: Create /etc/sysctl.d/k8s.conf 
>>>>>>> da51f1054f4a4e228288dd02cf5a314cb094e1c6:provisioning/ansible/roles/k8s-prerequisite/tasks/main.yaml
  ansible.builtin.copy:
    src: k8s_sysctl
    dest: /etc/sysctl.d/k8s.conf
  register: k8s_sysctl

- name: sysctl modules
  ansible.builtin.shell:
    cmd: sysctl -p /etc/sysctl.d/k8s.conf
  when: k8s_sysctl.changed is true

- name: Edit /etc/hosts file
  ansible.builtin.lineinfile:
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    path: "/etc/hosts"